---
- name: Deploy Application
  hosts: all
  become: true
  tasks:
    - name: Clone or update repository
      ansible.builtin.git:
        repo: "https://github.com/4Min4m/PaymentSimulator.git"
        dest: /home/ubuntu/PaymentSimulator
        version: main
        update: yes

    - name: Install dependencies
      ansible.builtin.shell: |
        cd /home/ubuntu/PaymentSimulator
        npm install
      args:
        chdir: /home/ubuntu/PaymentSimulator

    - name: Build the project
      ansible.builtin.shell: |
        cd /home/ubuntu/PaymentSimulator
        npm run build
      args:
        chdir: /home/ubuntu/PaymentSimulator

    - name: Restart application
      ansible.builtin.shell: |
        pm2 restart all || pm2 start npm --name " vite-react-typescript-starter" -- start
      args:
        chdir: /home/ubuntu/PaymentSimulator