name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Build the app
        run: npm run build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Ansible Playbook
        uses: stephane-klein/ansible-playbook-action@v0.4.0
        with:
          playbook: ansible/deploy.yml
        env:
          ANSIBLE_HOST_KEY_CHECKING: "False"
          SSH_PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
          INVENTORY: ansible/inventory.ini
